USE proadmin_ws;

ALTER TABLE individualevaluations DROP PRIMARY KEY;

ALTER TABLE leadevaluations DROP PRIMARY KEY;

ALTER TABLE reports DROP PRIMARY KEY;

ALTER TABLE runningteams DROP PRIMARY KEY;

ALTER TABLE academiclevels DROP PRIMARY KEY;

ALTER TABLE runnings DROP PRIMARY KEY;

ALTER TABLE studentteams DROP PRIMARY KEY;

ALTER TABLE teams DROP PRIMARY KEY;

ALTER TABLE students DROP PRIMARY KEY;

ALTER TABLE teachers DROP PRIMARY KEY;

ALTER TABLE projects DROP PRIMARY KEY;

COMMIT;