package com.sasd13.proadmin.content.extra;

public interface Extra {

    String EXIT = "EXIT";

    String MODE = "MODE";
    int MODE_NEW = 1;
    int MODE_EDIT = 2;

    String ID_PROJECT_CODE = "ID_PROJECT_CODE";
    String ID_TEACHER_NUMBER = "ID_TEACHER_NUMBER";
    String ID_STUDENT_NUMBER = "ID_STUDENT_NUMBER";
    String ID_TEAM_NUMBER = "ID_TEAM_NUMBER";
    String ID_RUNNING_YEAR = "ID_RUNNING_YEAR";
    String ID_ACADEMICLEVEL_CODE = "ID_ACADEMICLEVEL_CODE";
    String ID_REPORT_NUMBER = "ID_REPORT_NUMBER";

    String PARCEL_PROJECT = "PARCEL_PROJECT";
    String PARCEL_TEACHER = "PARCEL_TEACHER";
    String PARCEL_STUDENT = "PARCEL_STUDENT";
    String PARCEL_TEAM = "PARCEL_TEAM";
    String PARCEL_TEAM_STUDENT = "PARCEL_TEAM_STUDENT";
    String PARCEL_STUDENTTEAM = "PARCEL_STUDENTTEAM";
    String PARCEL_RUNNING = "PARCEL_RUNNING";
    String PARCEL_RUNNING_PROJECT = "PARCEL_RUNNING_PROJECT";
    String PARCEL_ACADEMICLEVEL = "PARCEL_ACADEMICLEVEL";
    String PARCEL_RUNNINGTEAM = "PARCEL_RUNNINGTEAM";
    String PARCEL_RUNNINGTEAM_RUNNING = "PARCEL_RUNNINGTEAM_RUNNING";
    String PARCEL_RUNNINGTEAM_TEAM = "PARCEL_RUNNINGTEAM_TEAM";
    String PARCEL_REPORT = "PARCEL_REPORT";
    String PARCEL_REPORT_RUNNINGTEAM = "PARCEL_REPORT_RUNNINGTEAM";
    String PARCEL_LEADEVALUATION = "PARCEL_LEADEVALUATION";
    String PARCEL_INDIVIDUALEVALUATION = "PARCEL_INDIVIDUALEVALUATION";
}
