SET search_path TO proadmin_db2;

ALTER TABLE individualevaluations DROP CONSTRAINT IF EXISTS pk_ie;

ALTER TABLE leadevaluations DROP CONSTRAINT IF EXISTS pk_le;

ALTER TABLE reports DROP CONSTRAINT IF EXISTS pk_rp;

ALTER TABLE runningteams DROP CONSTRAINT IF EXISTS pk_rntm;

ALTER TABLE academiclevels DROP CONSTRAINT IF EXISTS pk_al;

ALTER TABLE runnings DROP CONSTRAINT IF EXISTS pk_rn;

ALTER TABLE studentteams DROP CONSTRAINT IF EXISTS pk_sttm;

ALTER TABLE teams DROP CONSTRAINT IF EXISTS pk_tm;

ALTER TABLE students DROP CONSTRAINT IF EXISTS pk_st;

ALTER TABLE teachers DROP CONSTRAINT IF EXISTS pk_tc;

ALTER TABLE projects DROP CONSTRAINT IF EXISTS pk_pr;

--COMMIT;