USE proadmin_aaa;

CREATE TABLE users (
	_id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	_uid VARCHAR(255) NOT NULL,
	_username VARCHAR(255) NOT NULL,
	_password VARCHAR(255) NOT NULL,
	_status TINYINT NOT NULL DEFAULT 0,
	_roles VARCHAR(255) NOT NULL,
	_intermediary VARCHAR(50) NOT NULL,
	_email VARCHAR(255) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE preferences (
	_id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	_category VARCHAR(255) NOT NULL,
	_name VARCHAR(255) NOT NULL,
	_defaultvalue VARCHAR(255) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE userpreferences (
	_id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	_value VARCHAR(255) NOT NULL,
	_user BIGINT NOT NULL,
	_preference BIGINT NOT NULL
) ENGINE=InnoDB;

COMMIT;